# Generated by Django 5.1 on 2025-01-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
