# Generated by Django 5.1.5 on 2025-01-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_ingredient_alter_recipe_options_recipe_cook_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
