# Generated by Django 5.1.5 on 2025-01-21 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                choices=[
                    ("produce", "Produce"),
                    ("meat", "Meat"),
                    ("dairy", "Dairy"),
                    ("pantry", "Pantry"),
                    ("spices", "Spices"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cook_time",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("cup", "Cup"),
                    ("tbsp", "Tablespoon"),
                    ("tsp", "Teaspoon"),
                    ("oz", "Ounce"),
                    ("lb", "Pound"),
                    ("g", "Gram"),
                    ("kg", "Kilogram"),
                    ("ml", "Milliliter"),
                    ("l", "Liter"),
                    ("pinch", "Pinch"),
                    ("piece", "Piece"),
                    ("slice", "Slice"),
                    ("whole", "Whole"),
                ],
                max_length=50,
            ),
        ),
    ]
