# Generated by Django 5.1.5 on 2025-01-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_ingredient_category_alter_ingredient_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("cup", "Cup"),
                    ("tbsp", "Tablespoon"),
                    ("tsp", "Teaspoon"),
                    ("oz", "Ounce"),
                    ("lb", "Pound"),
                    ("g", "Gram"),
                    ("kg", "Kilogram"),
                    ("ml", "Milliliter"),
                    ("l", "Liter"),
                    ("pinch", "Pinch"),
                    ("piece", "Piece"),
                    ("whole", "Whole"),
                    ("pkg", "Package"),
                    ("slice", "Slice"),
                ],
                max_length=50,
            ),
        ),
    ]
