# Generated by Django 5.1.5 on 2025-02-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_mealplan_mealslot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mealslot",
            options={"ordering": ["date", "meal_type_order"]},
        ),
        migrations.AddField(
            model_name="mealslot",
            name="meal_type_order",
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
